### PR TITLE
CI

### PR DESCRIPTION
**Pull request by maumueller**
There we go with some continuous integration checking dataset creation, running algorithms, and running the tests. (There is one test that fail at the moment.)

### CODE REVIEW

**Comment by maumueller** [comment]
I don't even remember doing this PR. :-)  I'll see what needs to be done to get this compiling.

**Comment by maumueller** [comment]
So, rebasing and adapting to self-joins fixed the problems. However, there are a few tests that fail, can you take a look @Cecca?

**Comment by Cecca** [comment]
Will do

**Comment by Cecca** [comment]
The issue was that we now assume that all vectors are normalized, but the tests didn't enforce this assumption.

**Pull request merged**
